language: c
compiler: clang
branches:
    only:
        - travis
        - master
os:
    - linux
    - osx
sudo: false
addons:
    apt:
        sources:
            - kubuntu-backports
        packages:
            - cmake
env:
    - BUILD_SHARED_LIBS=ON
    - BUILD_SHARED_LIBS=OFF
script:
    - cmake -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} .
    - cmake --build .
notifications:
  email:
    recipients:
      - travis@glfw.org
    on_success: never
    on_failure: always
